travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,6 +16,9 @@ matrix:
     - os: osx
       compiler: clang
       sudo: false
+      before_install:
+        - set -e # Fail the whole script whenever any command fails
+        - git submodule update --init --recursive
       install:
         - |
           if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
@@ -33,12 +36,14 @@ matrix:
       env: COMPILER=g++-4.8 CMAKE_OPTIONS="-DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF"
       compiler: gcc
       before_install:
+        - set -e
+        - git submodule update --init --recursive
         - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
         - sudo apt-get install gcc-4.8 g++-4.8 libcap-dev
         - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
         - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
         - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
-        - sudo bash ./install_cmake.sh
+        - sudo bash ./rungcc.sh
       addons:
         apt:
           sources:
@@ -46,10 +51,6 @@ matrix:
           packages:
             - gcc-4.8
             - g++-4.8
-
-before_install:
-  - set -e # Fail the whole script whenever any command fails
-  - git submodule update --init --recursive
 
 script:
   - ${TRAVIS_BUILD_DIR}/ChiikaAPI/ThirdParty/log4cplus/configure
