travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,13 +1,8 @@
 language: cpp
+compiler: clang
+os: linux
+sudo:false
 
-compiler:
-  - clang
-  #- gcc
-
-osx_image: xcode7
-os:
-  - osx
-  #- linux
 
 git:
   submodules: false
@@ -15,20 +10,39 @@ git:
 env:
   - TARGET_ARCH=x64
 
-addons:
-  apt:
-    sources:
-    - ubuntu-toolchain-r-test
-    packages:
-    - clang
-    - cmake
+install:
+  - |
+    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
+      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
+      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
+    else
+      brew install cmake
+    fi
+
+matrix:
+  include:
+    - env: COMPILER=clang++-3.5 CMAKE_OPTIONS="-DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF"
+      addons: &clang35
+        apt:
+          packages: ["clang-3.5", "valgrind"]
+          sources: &sources
+            - ubuntu-toolchain-r-test
+            - llvm-toolchain-precise-3.5
+            - llvm-toolchain-precise-3.6
+            - llvm-toolchain-precise-3.7
+            - llvm-toolchain-precise
+    - os: osx
+      env: COMPILER=clang++
+      osx_image: xcode6.4
+
 
 before_install:
-  - export PATH=$(pwd)/cmake/bin:$PATH
+  - set -e # Fail the whole script whenever any command fails
   - git submodule update --init --recursive
 
 before_script:
-  - cmake --version
-  - cmake -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF .
+  - cd ${TRAVIS_BUILD_DIR}
+  - (mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} ${CMAKE_OPTIONS})
 
 script: make
